### ISSUE TITLE
請問還能動嗎？

### ISSUE THREAD

**Issue by GHolk** [wsmwason/gamer-to-rss#4]
目前的輸出：

```terminal
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"><channel><title>hp10000p 的小屋創作 RSS</title><link>http://home.gamer.com.tw/creation.php?owner=hp10000p</link><language>zh-tw</language><lastBuildDate>Thu, 19 Apr 2018 21:34:59 +0800</lastBuildDate><ttl>20</ttl></channel></rss>
```

就我 debug 的結果，應該是 
[63 行](https://github.com/wsmwason/gamer-to-rss/blob/master/GamerHomeCreation.php#L63)
那個 regexp 沒有 match 到。

你要修嗎？
不然我有空 (?) 可能會修……

另外目前會自己 host 一些 feed 在 github page 上，
就每天開機時排程更新推到 github 上。
<http://github.com/gholk/feed/>

**Comment by wsmwason** [comment]
之前有修正過了只是一直沒 Release 出來，目前已經把 v1.0 推上來囉！
